config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :pomodoros
  resources :links
  resources :nodes
  # resources :dashboard
  devise_for :users
  root "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/node.rb
class Node < ApplicationRecord
  before_destroy :check_if_root
  class Error < StandardError
  end

  has_many :pomodoro
  
  has_many :to_links, foreign_key: :from_id, class_name: :Link, dependent: :destroy
  has_many :to_nodes, through: :to_links  

  has_many :from_links, foreign_key: :to_id, class_name: :Link #tricky!
  has_many :from_nodes, through: :from_links

  belongs_to :project, optional: true

  accepts_nested_attributes_for :to_links

  def children_incomplete 
    self.from_nodes.where(complete: false).count > 0
  end

  def check_if_root
    unless destroyed_by_association
      root = Node.where(project_id: project_id).order(:created_at).limit(1).first.id
      if from_nodes.exists?
        raise Error.new "Can't delete parent node."
      end
      if id == root
        raise Error.new "Can't delete root node."
      end
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new(node_params)

    # if link_params
    #   if link_params[:parent_node]
    #     session[:parent_node] = link_params[:parent_node]
    #   end  
    # end
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        # if session[:parent_node]
        #   @link = Link.new(from_node: @node, to_node: Node.where(id: session[:parent_node]).first, project_id: node_params[:project_id])
        #   @link.save
        #   session[:parent_node] = nil
        # end
        format.html { redirect_to project_path(Project.where(id: @node.project_id).first, anchor: "n_#{@node.id}"), notice: 'Node was successfully created.' }
        # format.html { redirect_to projects_url, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        parent_project = @node.project
        format.html { redirect_to project_path(parent_project, anchor: "n_#{@node.id}"), notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    parent_project = @node.project
    parent_node = @node.to_nodes.first
    @node.destroy
    respond_to do |format|
      format.html { redirect_to project_path(parent_project, anchor: "n_#{parent_node.id}"), notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def node_params
      params.require(:node).permit(:name, :description, :project_id, :complete, to_links_attributes: [:to_id, :project_id])
    end

    # def link_params
    #   params.require(:link).permit(:parent_node)
    # end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_with(model: node, local: true) do |form| %>
  <% if node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
        <% node.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <%= form.fields_for :to_links do |to_links_form| %>
    <li>
      <%= to_links_form.label :from_id %>
      <%= to_links_form.text_field :from_id %>

      <%= to_links_form.label :to_id %>
      <%= to_links_form.text_field :to_id %>

      <%= to_links_form.label :project_id %>
      <%= to_links_form.text_field :project_id %>
    </li>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= node.description %></td>
        <td><%= node.project_id %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @node.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @node.project_id %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>