config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :pomodoros
  resources :links
  resources :nodes
  # resources :dashboard
  devise_for :users
  root "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pomodoro.rb
class Pomodoro < ApplicationRecord
  belongs_to :node
  has_rich_text :content
end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController
  before_action :set_pomodoro, only: [:show, :edit, :update, :destroy]

  # GET /pomodoros
  # GET /pomodoros.json
  def index
    @pomodoros = Pomodoro.where(node_id: pomodoro_params[:node_id])
  end

  # GET /pomodoros/1
  # GET /pomodoros/1.json
  def show
  end

  # GET /pomodoros/new
  def new
    @pomodoro = Pomodoro.new(pomodoro_params)
  end

  # GET /pomodoros/1/edit
  def edit
  end

  # POST /pomodoros
  # POST /pomodoros.json
  def create
    @pomodoro = Pomodoro.new(pomodoro_params)

    respond_to do |format|
      if @pomodoro.save
        format.html { redirect_to @pomodoro, notice: 'Pomodoro was successfully created.' }
        format.json { render :show, status: :created, location: @pomodoro }
      else
        format.html { render :new }
        format.json { render json: @pomodoro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pomodoros/1
  # PATCH/PUT /pomodoros/1.json
  def update
    respond_to do |format|
      if @pomodoro.update(pomodoro_params)
        format.html { redirect_to @pomodoro, notice: 'Pomodoro was successfully updated.' }
        format.json { render :show, status: :ok, location: @pomodoro }
      else
        format.html { render :edit }
        format.json { render json: @pomodoro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pomodoros/1
  # DELETE /pomodoros/1.json
  def destroy
    @pomodoro.destroy
    respond_to do |format|
      format.html { redirect_to pomodoros_url, notice: 'Pomodoro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pomodoro
      @pomodoro = Pomodoro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pomodoro_params
      params.require(:pomodoro).permit(:content, :node_id)
    end
end

app/helpers/pomodoros_helper.rb
module PomodorosHelper
end

app/views/pomodoros/_form.html.erb
<%= form_with(model: pomodoro, local: true) do |form| %>
  <% if pomodoro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pomodoro.errors.count, "error") %> prohibited this pomodoro from being saved:</h2>

      <ul>
        <% pomodoro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "form-control customized-min-height" %>
  </div>

  <div class="field">
    <%= form.label :node_id %>
    <%= form.number_field :node_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pomodoros/edit.html.erb
<h1>Editing Pomodoro</h1>

<%= render 'form', pomodoro: @pomodoro %>

<%= link_to 'Show', @pomodoro %> |
<%= link_to 'Back', pomodoros_path %>

app/views/pomodoros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pomodoros</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Node</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pomodoros.each do |pomodoro| %>
      <tr>
        <td><%= pomodoro.content %></td>
        <td><%= pomodoro.node_id %></td>
        <td><%= pomodoro.user_id %></td>
        <td><%= link_to 'Show', pomodoro %></td>
        <td><%= link_to 'Edit', edit_pomodoro_path(pomodoro) %></td>
        <td><%= link_to 'Destroy', pomodoro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pomodoro', new_pomodoro_path %>

app/views/pomodoros/new.html.erb
<h1>New Pomodoro</h1>

<%= render 'form', pomodoro: @pomodoro %>

<%= link_to 'Back', pomodoros_path %>

app/views/pomodoros/show.html.erb
<p id="notice"><%= notice %></p>


  <%= @pomodoro.content %>

<p>
  <strong>Node:</strong>
  <%= @pomodoro.node_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @pomodoro.user_id %>
</p>

<%= link_to 'Edit', edit_pomodoro_path(@pomodoro) %> |
<%= link_to 'Back', pomodoros_path %>