config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :pomodoros
  resources :links
  resources :nodes
  # resources :dashboard
  devise_for :users
  root "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :nodes, dependent: :destroy
  has_many :links, dependent: :destroy

  accepts_nested_attributes_for :nodes
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if current_user
      prjid = @project.id

      edges = Link.where(project_id: prjid).pluck("from_id, to_id")
      nodes = Node.where(project_id: prjid).pluck("id").push(-1)
      startnode = -1
      endnode = Node.where(project_id: prjid).order(:created_at).limit(1).first.id

      # Add an artificial start node
      startpoints = Node.where(project: prjid).includes(:from_links).references(:from_links).where(links: {id: nil}).pluck("id")
      edges += startpoints.map{|n| [startnode, n]}
      edges2 = edges.dup

      pnd = []
      nextnodes = [startnode]

      # p edges
      # p nodes
      # p startnode
      # p endnode
      # p nextnodes
      # p startpoints

      # return
      
      until nextnodes.empty?
        v = nextnodes[0]
        nextnodes.delete(v)
      
        neighboredges = edges.select{|e| e[0] == v }
        neighboredges.sort_by!{|x, y| y}
        pnd += neighboredges
      
        neighboredges.each{ |e|
          edges.delete(e)
          neighbor = e[1]
          incoming = edges.select{|e| e[1] == neighbor}
          p incoming
          if incoming.empty?
            nextnodes.push(neighbor)
          end
        }
      end
      
      prev = pnd[0][0]
      nest1 = 1
      pnd.map! { |e|
        if e[0] != prev
          nest1 += 1
          prev = e[0]
        end
        e = [e, nest1]
      }
      
      p pnd
      
      # pnd = [
      #   [[1, 2], 1],
      #   [[1, 3], 1],
      #   [[1, 4], 1],
      #   [[2, 3], 2],
      #   [[2, 5], 2],
      #   [[4, 5], 3],
      #   [[3, 5], 4]  
      # ]
      
      # nodes = [1, 2, 3, 4, 5, 6, 7, 8, 9]
      # pnd = [
      #   [[1, 2], 1],
      #   [[1, 3], 1],
      #   [[1, 4], 1],
      #   [[2, 5], 2],
      #   [[3, 5], 3],
      #   [[4, 5], 4],
      #   [[5, 6], 5],
      #   [[5, 7], 5],
      #   [[5, 8], 5],
      #   [[6, 9], 6],
      #   [[7, 9], 7],
      #   [[8, 9], 8],
      # ]
      
      table = Array.new(nodes.length*2){Array.new(1,0)}
      
      pnd.each{ |activity|
      
        puts "TABLE START"
        table.each{ |r|
          p r
        }
      
        startnode = activity[0][0]
        nest1s = activity[1]
      
        endnode = activity[0][1]
        ix = pnd.index { |a| a[0][0] == endnode }
      
        if ix
          nest1e = pnd[ix][1]
        else
          nest1e = nodes.length
        end
      
        ####
        nest1s *= 2
        nest1e *= 2
        ####
      
        puts "#{startnode},#{endnode}"
        x1 = table[nest1s - 1].index {|c| c != 0}
        x2 = table[nest1s - 2].index {|c| c != 0}
        x = x1 || x2
        unless x
          x = 0
        end
        cols = table.transpose
      
        found = false
        while x < cols.length do
          puts "colx"
          c2 = cols[x].clone
          c2[nest1e-1] = "E"
          c2[nest1s] = "S"
          p c2
          cols[x].delete_at(nest1e-1)
          cols[x].shift(nest1s)
          p cols[x]
          if cols[x].all?(0)
            table[nest1s-1][x] = startnode
            ###
            table[nest1e-2][x] = endnode
            ###
            found = true
            puts "found1"
            break
          end
          x += 1
        end
        until found do
          table.each{ |row|
            row.push(0)
          }
          cols = table.transpose
          cols[x].delete_at(nest1e-1)
          cols[x].shift(nest1s)
          if cols[x].all?(0)
            table[nest1s-1][x] = startnode
            ###
            table[nest1e-2][x] = endnode
            ###
            found = true
            puts "found2"
          end
          x += 1    
        end
      
        puts "TABLE END"
        table.each{ |r|
          p r
        }
      }
      
      puts "FINAL TABLE"
      table.each{ |r|
        puts r.join("\t")
      }
      
      # return "exit"
      
      plot = Array.new()
      
      plot.push(Array.new(table[0].length,"   "))
      i = 1
      table_index = 0
      cols = table.transpose
      
      (table.length/2).times{
        5.times{
          plot.push(Array.new(table[0].length,"   "))
        }
      
        row_incoming = table[table_index]
        row_outgoing = table[table_index + 1]
      
        incoming_first = row_incoming.index{|c| c != 0}
        outgoing_first = row_outgoing.index{|c| c != 0}
      
        if incoming_first.nil?
          first = outgoing_first
          node = row_outgoing[outgoing_first]
        elsif outgoing_first.nil?
          first = incoming_first
          node = row_incoming[incoming_first]
        else
          first = [incoming_first, outgoing_first].min
          node = row_incoming[incoming_first]
        end
      
        start_in = false
        first_in = true
        puts "row in #{row_incoming}"
      
        row_incoming.reverse.each_with_index{ |ri, j|
          ix = row_incoming.length - 1 - j
          if ix == first
            plot[i][ix] = "---"
            plot[i+1][ix] = node
            break
          end
          if ri != 0
            start_in = true
          end
          if start_in
            if first_in
              plot[i][ix] = "<< "
              first_in = false
            else
              if ri != 0
                plot[i][ix] = "<v<"
              else
                plot[i][ix] = "<<<"
              end
            end
          end
        }
      
        start_in = false
        first_in = true
        row_outgoing.reverse.each_with_index{ |ro, j|
          ix = row_incoming.length - 1 - j
          if ix == first
            plot[i+2][ix] = "---"
            break
          end
          if ro != 0
            start_in = true
          end
          if start_in
            if first_in
              plot[i+2][ix] = ">> "
              first_in = false
            else
              if ro != 0
                plot[i+2][ix] = ">v>"
              else
                plot[i+2][ix] = ">>>"
              end
            end
          end
        }
      
        puts "in #{row_incoming}"
        puts "ot #{row_outgoing}"
      
        table_index += 2
        i += 5
      }
      
      table[0].length.times{ |col|
        puts "col ||| #{col}"
        i = 1
        inside = false
        first_inside = true
        (table.length/2).times{ |row|
          row_ix = row * 2
          incoming = table[row_ix][col]
          outgoing = table[row_ix+1][col]
          # puts "in #{incoming}"
          # puts "out #{outgoing}"
          if incoming != 0
            inside = false
            first_inside = true
          end
          if outgoing != 0
            inside = true
          end
          # break if i+4 > plot.length - 1
          if inside
            if first_inside
              # plot[i][ix] = " v "
              # plot[i+1][ix] = " v "
              # plot[i+2][ix] = " v "
              plot[i+3][col] = " v "
              plot[i+4][col] = " v "
              first_inside = false
            else
              5.times{|r|
                if plot[i+r][col] == "   "
                  plot[i+r][col] = " v "
                elsif plot[i+r][col] == ">>>"
                  plot[i+r][col] = ">+>"
                elsif plot[i+r][col] == "<<<"
                  plot[i+r][col] = "<+<"
                end
              }  
            end
          end
          # puts " #{plot[i][col]}"
          # puts " #{plot[i+1][col]}"
          # puts " #{plot[i+2][col]}"
          # puts " #{plot[i+3][col]}"
          # puts " #{plot[i+4][col]}"
          # puts "col"
          # gets
          i += 5
        }
      }

      # puts "PLOT"
      # plot.each{ |r|
      #   puts r.join
      # }

      p edges2
      p nodes
      p endnode

      # i = 7
      # n1 = nil
      # n2 = nil
      # pl = plot.length

      # while i+5 < pl do
      #   puts "Testing nodes, i = #{i}"
      #   j = plot[i].index{|x| x.class == Integer}
      #   above = plot[i-2][j]
      #   below = plot[i+2][j]
      #   above_corner = plot[i-1][j+1]
      #   below_corner = plot[i+1][j+1]
      
      #   p above
      #   p below
      #   p above_corner
      #   p below_corner
      
      #   if above == " v " && below == " v " && above_corner[0] != "<" && below_corner[0] != ">"
      #     p "Found first node"
      #     n1 = [i,j]
      #   end
      
      #   if n1
      #     s = i + 5
      #     t = plot[s].index{|x| x.class == Integer}
      #     above = plot[s-2][t]
      #     below = plot[s+2][t]
      #     above_corner = plot[s-1][t+1]
      #     below_corner = plot[s+1][t+1]
        
      #     if above == " v " && below == " v " && above_corner[0] != "<" && below_corner[0] != ">"
      #       p "Found second node"
      #       n2 = [s,t]
      #     else
      #       n2 = nil
      #     end

      #     puts "n1"
      #     p n1
      #     puts "n2"
      #     p n2
      
      #     if n1 && n2
      #       p "Check if nodes are compatible for sliding"
      #       r1 = n1[0]
      #       c1 = n1[1]
      
      #       r2 = n2[0]
      #       c2 = n2[1]
      
      #       compare_row1_1 = plot[r1-1].map{|x| x == "---" || x.class == Integer ? " v " : x}
      #       compare_row1_2 = plot[r1].map{|x| x == "---" || x.class == Integer ? " v " : x}
      #       compare_row1_3 = plot[r1+1].map{|x| x == "---" || x.class == Integer ? " v " : x}
      
      #       compare_row2_1 = plot[r2-1].map{|x| x == "---" || x.class == Integer ? " v " : x}
      #       compare_row2_2 = plot[r2].map{|x| x == "---" || x.class == Integer ? " v " : x}
      #       compare_row2_3 = plot[r2+1].map{|x| x == "---" || x.class == Integer ? " v " : x}
      

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <%= form.fields_for :nodes do |nodes_form| %>
    <li>
      <%= nodes_form.label :name %>
      <%= nodes_form.text_field :name %>
    </li>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path(project: {name: "", description: "", user_id: current_user.id, nodes_attributes: [{name: ""}] }) %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1>Work breakdown structure</h1>

    <svg class="defs-only" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" >
      <symbol id="right-down">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 L 20 10" stroke="black" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
          <path vector-effect="non-scaling-stroke" d="M 0 10 Q 10 10 10 20" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="up-left">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 L 20 10" stroke="black" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
          <path vector-effect="non-scaling-stroke" d="M 10 0 Q 10 10 0 10" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="right">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 L 20 10" stroke="black" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="left">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 L 20 10" stroke="black" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="down-elbow">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 Q 10 10 10 20" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="up-elbow">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 10 0 Q 10 10 0 10" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="down">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 10 0 L 10 20" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="right-cross">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 L 20 10" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
          <path vector-effect="non-scaling-stroke" d="M 10 0 L 10 6 Q 10 8, 12 8 T 14 10 Q 14 12, 12 12 T 10 14 M 10 14 L 10 20 " stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
        </svg>
      </symbol>
      <symbol id="left-cross">
        <svg viewBox="0 0 20 20" preserveAspectRatio="none" stroke-width="2">
          <path vector-effect="non-scaling-stroke" d="M 0 10 L 20 10" stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>
          <path vector-effect="non-scaling-stroke" d="M 10 0 L 10 6 Q 10 8, 12 8 T 14 10 Q 14 12, 12 12 T 10 14 M 10 14 L 10 20 " stroke="black" fill="none" transform="rotate(90,10,10) scale(1, -1) translate(0, -20)"/>        </svg>
      </symbol>
    </svg>

<% root_node = @root_n %>
<div class="d-flex flex-wrap align-content-between justify-content-around m-5">
  <div class="rounded bg-primary opacity-90 p-3 mt-5 mb-5 ml-1 mr-1 node" id="n_<%= root_node.id %>">
    <h2><%= root_node.name %></h2>
    <%= form_with(model: root_node) do |form| %>
      <div class="field">
      <%= form.label :complete %>
      <%= form.check_box :complete, onchange: 'this.form.submit();' %>
      </div>
    <% end %>
    <% if root_node.description then %>
    <p><%= root_node.description %></p>
    <% end %>
    <p><%= link_to 'Add subtask', new_node_path(node: {project_id: @project.id, to_links_attributes: [{to_id: root_node.id, project_id: @project.id}]}), class: "btn btn-primary btn-sm text-white"%></p>
  </div>
</div>
<div style="width: <%= @grid[0].length * 70 %>px;">
<div style="display: grid; width: auto; grid-template-columns: repeat(<%= @grid[0].length %>, minmax(40px, min-content)); grid-auto-rows: minmax(40px, auto);">
<% @grid.each{ |r| %>
  <% r.each{ |c|%>
  <div class="">
  <% if c == -1 %>
    START
  <% elsif c.class == Integer %>
    <% node = Node.find_by(id: c) %>
    <div style="white-space: nowrap;"><%= node.name %></div>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter<%= node.id %>">
    go
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter<%= node.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModal<%= node.id %>CenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">


          <div class="rounded <%= node.children_incomplete ? "bg-secondary" : ( node.complete ? "bg-success" : "bg-warning" ) %> opacity-90 p-3 mt-5 mb-5 ml-1 mr-1 node" id="n_<%= node.id %>">
            <h2><%= node.name %></h2>
            <%= form_with(model: node) do |form| %>
              <div class="field">
              <%= form.label :complete %>
              <%= form.check_box :complete, onchange: 'this.form.submit();' %>
              </div>
            <% end %>
            <% if node.description then %>
            <p><%= node.description %></p>
            <% end %>

            <p>
            <%= link_to 'Start Pomodoro', new_pomodoro_path(pomodoro: {node_id: node.id}), class: "btn btn-primary btn-sm text-white m-1"%>
            <%= link_to 'View pomodoros', pomodoros_path(pomodoro: {node_id: node.id}), class: "btn btn-primary btn-sm text-white m-1" %>
            </p>

            <p>
            <%= link_to 'Add subtask', new_node_path(node: {project_id: @project.id, to_links_attributes: [{to_id: node.id, project_id: @project.id}]}), class: "border-white btn btn-warning btn-sm text-black m-1"%>
            <%= link_to 'Edit task', edit_node_path(node), class: "btn btn-warning btn-sm text-black m-1 border-white"%>
            <%= link_to 'Connect to task', new_link_path(link: {from_id: node.id, project_id: @project.id}, anchor: "n_#{node.id}"), class: "border-white btn btn-warning btn-sm text-black m-1" %>
            </p>

            </p>
            <% unless node.from_nodes.exists? %>
            <%= link_to 'Delete this node', node, method: :delete, class: "btn btn-danger btn-sm text-white m-1" %>
            <% end %>
            <div class="dropdown d-inline-block m-1">
              <button class="btn btn-danger btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Delete links
              </button>
              <div class="dropdown-menu">
                <% if node.to_links.count > 1 %>
                  <% node.to_links.each { |to_link| %>
                    <%= link_to "Delete link to #{to_link.to_node.name}", to_link, method: :delete, class: "btn btn-danger btn-sm text-white link_delete mb-2", id: "l_#{to_link.from_id}_#{to_link.to_id}" %>
                  <% } %>
                <% end %>
                <% node.from_links.each { |from_link| %>
                  <% if from_link.from_node.to_links.count > 1 %>
                    <%= link_to "Delete link from #{from_link.from_node.name}", from_link, method: :delete, class: "btn btn-danger btn-sm text-white link_delete mb-2", id: "l_#{from_link.from_id}_#{from_link.to_id}" %>
                  <% end %>
                <% } %>
              </div>
            </div>
            </p>
          </div>



          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>


  <% elsif c != "---" %>
      <svg  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 100 20" preserveAspectRatio="none" style="width: 100%; height: 100%;" class="bg-2">

    <% if c == ">>>"%>

      <use xlink:href="#right"/>
 
    <% elsif c == ">v>"%>

      <use xlink:href="#right-down"/>
 
    <% elsif c == ">> " %>

      <use xlink:href="#down-elbow"/>

    <% elsif c == ">+>" %>

      <use xlink:href="#right-cross"/>

    <% elsif c == "<<<" %>

      <use xlink:href="#left"/>

    <% elsif c == "<< " %>

      <use xlink:href="#up-elbow"/>

    <% elsif c == "<+<" %>

      <use xlink:href="#left-cross"/>

    <% elsif c == "<v<" %>

      <use xlink:href="#up-left"/>

    <% elsif c == " v " %>

      <use xlink:href="#down"/>

    <% end %>
      </svg>
  <% end %>
  </div>
  <%}%>
<%}%>
</div>

<svg xmlns="http://www.w3.org/2020/svg" id="svg_bg" style="width:100%; position: absolute; top: 0; z-index: -1;">
  <defs>
    <marker id="arrowheadfuchsia" viewBox="0 0 10 10" refX="3" refY="5" markerWidth="6" markerHeight="6" orient="auto" stroke="fuchsia" fill="fuchsia">
      <path d="M 0 0 L 10 5 L 0 10 z" />
    </marker>
    <marker id="arrowheadcyan" viewBox="0 0 10 10" refX="3" refY="5" markerWidth="6" markerHeight="6" orient="auto" stroke="cyan" fill="cyan">
      <path d="M 0 0 L 10 5 L 0 10 z" />
    </marker>
    <marker id="arrowheadblack" viewBox="0 0 10 10" refX="3" refY="5" markerWidth="6" markerHeight="6" orient="auto" stroke="black" fill="black">
      <path d="M 0 0 L 10 5 L 0 10 z" />
    </marker>
    <marker id="arrowheadorange" viewBox="0 0 10 10" refX="3" refY="5" markerWidth="6" markerHeight="6" orient="auto" stroke="orange" fill="orange">
      <path d="M 0 0 L 10 5 L 0 10 z" />
    </marker>
  </defs>
  <g fill="none" stroke="black" stroke-width="4" marker-end="url(#arrowheadblack)">

  </g>
</svg>

<script>
  const edges = <%= @edges.to_s %>;
  const nodes = <%= @nodes.to_s %>
</script>

<%= javascript_pack_tag 'arrows' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>